name: CI
on:
  push: { branches: [dev] }
  pull_request: { branches: [dev, main] }
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip
      - run: pip install -e .[dev] || pip install -r requirements.txt
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Tests
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml
